### ISSUE TITLE
support multiple admins

### ISSUE THREAD

**Issue by gildesmarais** [gildesmarais/ansible-5-minutes-server#20]
Currently there's one ADMIN user.

This could encourage to share this admin user across organisations which is bad (e.g. can't audit who *really* logged in).

- [ ] secrets: remove `ADMIN_*`
- [ ] check if there's an existing playbook for user and key management - prefer to use that, if popular
- [ ] make ADMINS an array taking a hash like this (pseudo/draft code):
  ```yml
  ADMINS:
    - username: foo
      email: foo@bar.baz
      public_key: a/path/to/id_rsa.pub
  ```
- [ ] implement the creation and ssh key uploading in the role. (proper key management - needs to remove keys, when removed from `ADMINS` config)
- [ ] research if a go-to rolebook for that case exists in the ansible universe
